version: 2.1

orbs:
  python: circleci/python@0.2.1
  
executors:
  docker-executor:
    docker:
      - image: circleci/python:[3.9]
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

jobs:
  build-and-test:
    working_directory: ~/Assignment-3
    executor: docker-executor
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: main.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
