version: 2.1
jobs:
  run-tests:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command:
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV &&
            pip install --user -r requirements.txt && 
            python3 -m nltk.downloader all
      - run: 
          name: Pytest Unit Tests
          command:
            pytest --junitxml=test-reports/junit.xml tests/
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  build_test:
    jobs:
      - run-tests